global:
  external_labels:
    site: prod
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'node_exporter1'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.122.128:9100']
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.122.128:9113']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.122.128:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.122.128:9115
  - job_name: 'mysqld_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.122.128:9104']
  - job_name: 'php-fpm'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.122.128:9253']

