global:
  resolve_timeout: 1m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 30m
  receiver: 'telegrampush'
  routes:
  - receiver: 'telegramcritical'
    group_wait: 10s
    matchers:
    - severity="critical"
  - receiver: 'telegrampush'
    group_wait: 30s
    matchers:
    - severity="warning"

receivers:
  - name: 'telegrampush'
    telegram_configs:
    - chat_id: -1002330786938
      api_url: "https://api.telegram.org"
      send_resolved: true
      parse_mode: HTML
      bot_token: 7998806067:AAHw8WIFyVRhcscBiuAhFPcq5lWYfkCbRHY
  - name: 'telegramcritical'
    telegram_configs:
    - chat_id: -1002555994876
      api_url: "https://api.telegram.org"
      send_resolved: true
      parse_mode: HTML
      bot_token: 7838924766:AAFpRBb-Kkngfkp4zFERLO6PJB8UIWR1S-4

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['component', 'instance']
